[workspace]
members = [
    "crates/krill-daemon",
    "crates/krill-tui",
    "crates/krill-common",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Your Name <you@example.com>"]

[profile.release]
opt-level = 3
lto = true
codegen_units = 1
panic = 'abort'
