[workspace]
authors = ["Tommaso Pardi <tommaso.pardi@gmail.com>"]
channels = ["conda-forge"]
name = "lidar"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
start = "echo 'Starting lidar'"
stop = "echo 'Stopping lidar'"

[dependencies]
