[project]
name = "krill-pixi-test"
version = "0.1.0"
description = "Example pixi project for krill"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[dependencies]
python = ">=3.11"

[tasks]
run-lidar = "python scripts/logger.py lidar"
run-sensor = "python scripts/logger.py sensor"
