[workspace]
name = "decision-controller"
version = "0.1.0"
description = "Decision control service for robot example"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
python = ">=3.9"

[tasks]
run-controller = "python -u controller.py"
